### ISSUE TITLE
Compatible with content_type_whitelist?

### ISSUE THREAD

**Issue by ehannes** [y9v/carrierwave-base64#40] opened 2016-10-28 13:12 UTC
Using this gem, can I use carrierwave's `content_type_whitelist` somehow?

**Comment by lebedev-yury** [comment] 2016-11-01 15:09
actually this should work already, if you defined `content_type_whitelist` in your uploader

**Comment by ehannes** [comment] 2016-11-02 06:21
I tried it, but I didn't get it to work. I declared it as following in my uploader:
```
def content_type_whitelist
  %w(pdf/application)
end
```
and then uploading a pdf file, but it was rejected due to incorrect content type.

**Comment by jflewis** [comment] 2016-12-14 17:03
I'm having the same issue. Using this in my Uploader.
```ruby
def content_type_whitelist
    /image\//
end
```

Is there any status on this?

**Comment by lebedev-yury** [comment] 2016-12-15 09:44
Planning to work on this in this weekend.

**Comment by bobishh** [comment] 2017-06-06 15:16
Issue won't reproduce with current version of gem (2.5.3 at the moment) and carrierwave v1.1.0, tested with rails 5.1 and 4.2.8

**Comment by lebedev-yury** [comment] 2017-06-06 19:34
@bobishh Dis you set the `content_type_whitelist` to an array of extensions? I think it did not work for @ehannes and @jflewis because they tried to use MIME types for the whitelist

**Comment by bobishh** [comment] 2017-06-06 20:51
I've tried both ways - regex and array (except not with pdf but with image/png and image/jpeg), and it worked in all cases ¯\_(ツ)_/¯

**Comment by lebedev-yury** [comment] 2017-06-07 03:58
@bobishh okey, thank you, I'm closing this issue then

**Comment by ehannes** [comment] 2017-07-12 19:35
Great! If I have the time to check I will let you know if I can solve this issue by upgrading the gems.

**Comment by ehannes** [comment] 2017-08-24 18:13
@bobishh @lebedev-yury  I still fail to get this to work. I guess I'm doing some stupid mistake... I had a look at the [readme for the `ContentTypeWhitelist` module](http://www.rubydoc.info/gems/carrierwave/CarrierWave/Uploader/ContentTypeWhitelist) in CarrierWave and if I understand it correctly, I would be able to write something like this:
```
def content_type_whitelist
  %w(pdf/application image/jpg image/jpeg image/png)
end
```

If I add the above code and then try to attach a pdf file to the attachment, it fail with the following error: `en.errors.messages.content_type_whitelist_error`. If I remove the `content_type_whitelist` method from my uploader, I can once again attach pdf files.

**Comment by ehannes** [comment] 2017-08-24 18:31
I have solved the mystery. I tried in the console and it worked. Then I thought maybe something is wrong with my tests, and I were correct. Before I added the file with `Rack::Test::UploadedFile.new(file_path)`. If I tried a simple `File.open(file_path)` it worked. I guess I stick with the `File.open` for now on, or do you have any better suggestions?

**Comment by ehannes** [comment] 2017-08-24 19:53
Sorry to bother you again but now when I tried a real upload, it still doesn't work, (though my tests are now working). I guess that means that the error is in the frontend. I'll have to continue my research... I'll be back if I get it to work. If someone wants to look at it, this is my parameters sent to the controller:

```
Parameters: {"profile"=>{..., "attachment"=>"data:application/pdf;base64,JVBERi0xLjQKJc...
```

This is the error I get:
```
en.errors.messages.content_type_whitelist_error
```

This is my content_type_whitelist:
```
def content_type_whitelist
  %w(application/pdf image/jpeg image/png)
end
```

**Comment by lebedev-yury** [comment] 2017-08-25 09:17
@ehannes the parameters look fine. I will take a look at the issue, if I will find time on this weekend

**Comment by goelinsights** [comment] 2018-03-22 08:51
@ehannes did you figure out what was going on or how to figure out the file name the whitelist is checking against?

Have a similar issue where I'm getting the error: You are not allowed to upload "" files, allowed types: image/jpg, image/jpeg, image/png", so it's stripping out the mime type somewhere and leaving it blank - would love some troubleshooting help.

My JSON file being submitted: 
{id: 2057, image: "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAASABIAAD…du8xO+QR825cZHToMAVmNPNM52KFBHTPHHuaPNmiTWh//2Q==", image_filename: "ABCD_1.jpg"}

**Comment by ehannes** [comment] 2018-04-09 11:48
@goelinsights No, actually I have not fixed this yet...

**Comment by JamesAndresCM** [comment] 2018-10-12 10:35
alternative to validate content_type : 
Add in gemfile : 
`gem 'cocaine', '~> 0.5.8'`
`gem 'file_validators'`

Add in model :
`validates :img, file_size: { in: 100.bytes..1.megabyte }, file_content_type: { allow: ['image/jpeg', 'image/png', 'image/jpg'], mode: :strict }`

**Closed** 2024-06-25 18:38 UTC
Labels: help wanted
